### ISSUE TITLE
nil data object in SBBNetworkManager causes a crash.

### ISSUE THREAD

**Issue by jwarmkessel** [Sage-Bionetworks/Bridge-iOS-SDK#34]
I'm working on the MyHeartCounts app and I noticed a crasher while I was flying from NY back to SJ.
On line 420 of the SBBNetworkManager, if the data object that is being used in

NSDictionary * responseObject = [NSJSONSerialization JSONObjectWithData:data options:0 error:NULL];

is nil the application will crash.

**Comment by Erin-Mounts** [comment]
Thanks! Looking into it now.
